services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  
  kafka-setup:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-setup
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        cub kafka-ready -b kafka:29092 1 30 &&
        echo 'Creating topics...' &&
        kafka-topics --create --if-not-exists --topic registration --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic like --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic view --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic comment --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
        echo 'Topics created successfully'
      "
  api_service:
    build: 
      context: ./api_service
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - promocode_service
    volumes:
      - grpc_generated:/generated
      - ./user_service:/app/user_service
    environment:
      PROMOCODE_SERVICE_HOST: promocode_service:50052

  user_service:
    build: 
      context: ./user_service
      dockerfile: DockerFile
    ports:
      - "8001:8001"
    depends_on:
      - user_db
      - kafka-setup
    environment:
      DATABASE_URL: "postgresql://jinyuz:password@user_db:5432/userdb"
  
  promocode_service:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - promocode_db
      - kafka-setup
      - stats_service
    volumes:
      - grpc_generated:/generated
    environment:
      - DATABASE_URL: "postgresql://jinyuz:password@promocode_db:5432/promocodedb"
      - STATS_SERVICE_HOST=stats_service
      - STATS_SERVICE_PORT=50051


  user_db:
    image: postgres:13
    environment:
      POSTGRES_USER: jinyuz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
  promocode_db:
    image: postgres:13
    environment:
      POSTGRES_USER: jinyuz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: promocodedb
    ports:
      - "5435:5432"
    volumes:
      - promocode_db_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  stats_service:
    build:
      context: ./stats_service
    container_name: stats_service
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    depends_on:
      - kafka
      - clickhouse
    ports:
      - "50051:50051" 

networks:
  default:
    name: my_network
volumes:
  user_db_data:
  promocode_db_data:
  grpc_generated:
  clickhouse_data:


