services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
  api_service:
    build: 
      context: ./api_service
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - promocode_service
    volumes:
      - grpc_generated:/generated
      - ./user_service:/app/user_service
    environment:
      PROMOCODE_SERVICE_HOST: promocode_service:50052

  user_service:
    build: 
      context: ./user_service
      dockerfile: DockerFile
    ports:
      - "8001:8001"
    depends_on:
      - user_db
    environment:
      DATABASE_URL: "postgresql://jinyuz:password@user_db:5432/userdb"
  
  promocode_service:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - promocode_db
    volumes:
      - grpc_generated:/generated
    environment:
      DATABASE_URL: "postgresql://jinyuz:password@promocode_db:5432/promocodedb"


  user_db:
    image: postgres:13
    environment:
      POSTGRES_USER: jinyuz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
  promocode_db:
    image: postgres:13
    environment:
      POSTGRES_USER: jinyuz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: promocodedb
    ports:
      - "5435:5432"
    volumes:
      - promocode_db_data:/var/lib/postgresql/data

networks:
  default:
    name: my_network
volumes:
  user_db_data:
  promocode_db_data:
  grpc_generated: