services:
  api_service:
    build: 
      context: ./api_service
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    depends_on:
      - user_service

  user_service:
    build: 
      context: ./user_service
      dockerfile: DockerFile
    ports:
      - "8001:8001"
    depends_on:
      - user_db
    environment:
      DATABASE_URL: "postgresql://jinyuz:password@user_db:5432/userdb"

  user_db:
    image: postgres:13
    environment:
      POSTGRES_USER: jinyuz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5433:5433"
    volumes:
      - user_db_data:/var/lib/postgresql/data

networks:
  default:
    name: my_network
volumes:
  user_db_data: