# Dockerfile для promocode_service
FROM python:3.9-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Копируем весь код
COPY . /app/

CMD ["python", "promocode_service.py"]
