# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import promocodes.promocode_pb2 as promocode__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in promocode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PromocodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePromocode = channel.unary_unary(
                '/promocode.PromocodeService/CreatePromocode',
                request_serializer=promocode__pb2.CreatePromocodeRequest.SerializeToString,
                response_deserializer=promocode__pb2.Promocode.FromString,
                _registered_method=True)
        self.DeletePromocode = channel.unary_unary(
                '/promocode.PromocodeService/DeletePromocode',
                request_serializer=promocode__pb2.DeletePromocodeRequest.SerializeToString,
                response_deserializer=promocode__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.UpdatePromocode = channel.unary_unary(
                '/promocode.PromocodeService/UpdatePromocode',
                request_serializer=promocode__pb2.UpdatePromocodeRequest.SerializeToString,
                response_deserializer=promocode__pb2.Promocode.FromString,
                _registered_method=True)
        self.GetPromocode = channel.unary_unary(
                '/promocode.PromocodeService/GetPromocode',
                request_serializer=promocode__pb2.GetPromocodeRequest.SerializeToString,
                response_deserializer=promocode__pb2.Promocode.FromString,
                _registered_method=True)
        self.ListPromocodes = channel.unary_unary(
                '/promocode.PromocodeService/ListPromocodes',
                request_serializer=promocode__pb2.ListPromocodesRequest.SerializeToString,
                response_deserializer=promocode__pb2.ListPromocodesResponse.FromString,
                _registered_method=True)


class PromocodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePromocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePromocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePromocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPromocodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromocodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePromocode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePromocode,
                    request_deserializer=promocode__pb2.CreatePromocodeRequest.FromString,
                    response_serializer=promocode__pb2.Promocode.SerializeToString,
            ),
            'DeletePromocode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePromocode,
                    request_deserializer=promocode__pb2.DeletePromocodeRequest.FromString,
                    response_serializer=promocode__pb2.DeleteResponse.SerializeToString,
            ),
            'UpdatePromocode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePromocode,
                    request_deserializer=promocode__pb2.UpdatePromocodeRequest.FromString,
                    response_serializer=promocode__pb2.Promocode.SerializeToString,
            ),
            'GetPromocode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromocode,
                    request_deserializer=promocode__pb2.GetPromocodeRequest.FromString,
                    response_serializer=promocode__pb2.Promocode.SerializeToString,
            ),
            'ListPromocodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPromocodes,
                    request_deserializer=promocode__pb2.ListPromocodesRequest.FromString,
                    response_serializer=promocode__pb2.ListPromocodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'promocode.PromocodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('promocode.PromocodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromocodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePromocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promocode.PromocodeService/CreatePromocode',
            promocode__pb2.CreatePromocodeRequest.SerializeToString,
            promocode__pb2.Promocode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePromocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promocode.PromocodeService/DeletePromocode',
            promocode__pb2.DeletePromocodeRequest.SerializeToString,
            promocode__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePromocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promocode.PromocodeService/UpdatePromocode',
            promocode__pb2.UpdatePromocodeRequest.SerializeToString,
            promocode__pb2.Promocode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promocode.PromocodeService/GetPromocode',
            promocode__pb2.GetPromocodeRequest.SerializeToString,
            promocode__pb2.Promocode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPromocodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promocode.PromocodeService/ListPromocodes',
            promocode__pb2.ListPromocodesRequest.SerializeToString,
            promocode__pb2.ListPromocodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
