# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: promocode.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'promocode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpromocode.proto\x12\tpromocode\":\n\tPromocode\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\";\n\x16\x43reatePromocodeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"$\n\x16\x44\x65letePromocodeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"G\n\x16UpdatePromocodeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"!\n\x13GetPromocodeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x17\n\x15ListPromocodesRequest\"B\n\x16ListPromocodesResponse\x12(\n\npromocodes\x18\x01 \x03(\x0b\x32\x14.promocode.Promocode\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x98\x03\n\x10PromocodeService\x12J\n\x0f\x43reatePromocode\x12!.promocode.CreatePromocodeRequest\x1a\x14.promocode.Promocode\x12O\n\x0f\x44\x65letePromocode\x12!.promocode.DeletePromocodeRequest\x1a\x19.promocode.DeleteResponse\x12J\n\x0fUpdatePromocode\x12!.promocode.UpdatePromocodeRequest\x1a\x14.promocode.Promocode\x12\x44\n\x0cGetPromocode\x12\x1e.promocode.GetPromocodeRequest\x1a\x14.promocode.Promocode\x12U\n\x0eListPromocodes\x12 .promocode.ListPromocodesRequest\x1a!.promocode.ListPromocodesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'promocode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMOCODE']._serialized_start=30
  _globals['_PROMOCODE']._serialized_end=88
  _globals['_CREATEPROMOCODEREQUEST']._serialized_start=90
  _globals['_CREATEPROMOCODEREQUEST']._serialized_end=149
  _globals['_DELETEPROMOCODEREQUEST']._serialized_start=151
  _globals['_DELETEPROMOCODEREQUEST']._serialized_end=187
  _globals['_UPDATEPROMOCODEREQUEST']._serialized_start=189
  _globals['_UPDATEPROMOCODEREQUEST']._serialized_end=260
  _globals['_GETPROMOCODEREQUEST']._serialized_start=262
  _globals['_GETPROMOCODEREQUEST']._serialized_end=295
  _globals['_LISTPROMOCODESREQUEST']._serialized_start=297
  _globals['_LISTPROMOCODESREQUEST']._serialized_end=320
  _globals['_LISTPROMOCODESRESPONSE']._serialized_start=322
  _globals['_LISTPROMOCODESRESPONSE']._serialized_end=388
  _globals['_DELETERESPONSE']._serialized_start=390
  _globals['_DELETERESPONSE']._serialized_end=423
  _globals['_PROMOCODESERVICE']._serialized_start=426
  _globals['_PROMOCODESERVICE']._serialized_end=834
# @@protoc_insertion_point(module_scope)
